version: '3.8'

services:
  traefik:
    image: traefik:v3.0
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - traefik-certificates:/letsencrypt
    networks:
      - traefik-public
    environment:
      - ACME_EMAIL=${ACME_EMAIL:-admin@example.com}
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN:-localhost}`)"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.entrypoints=websecure"
        - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
        - "traefik.http.routers.dashboard.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_ADMIN_USER:-admin:$$apr1$$password}"
        - "traefik.http.services.dashboard.loadbalancer.server.port=8080"

networks:
  traefik-public:
    driver: overlay
    external: true

volumes:
  traefik-certificates:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/projects/raqeem/traefik/letsencrypt
